# Generated by Django 6.0.2 on 2026-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_photo',
            field=models.FileField(blank=True, null=True, upload_to='id_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_doc',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
