# Generated by Django 6.0.2 on 2026-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_id_photo_user_verification_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
