# Generated by Django 6.0.2 on 2026-04-03 05:59

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('module_code', models.CharField(max_length=10)),
                ('resource_type', models.CharField(choices=[('LECTURE_NOTES', 'Lecture Notes'), ('PAST_PAPER', 'Past Paper'), ('TUTORIAL_ANSWER', 'Tutorial Answer'), ('SHORT_NOTE', 'Short Note')], max_length=20)),
                ('file', models.FileField(upload_to=core.models.resource_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
