# Generated by Django 6.0.2 on 2026-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_useractivity_user_studyresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyresource',
            name='academic_stream',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
