# Generated by Django 6.0.2 on 2026-04-04 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studyresource_academic_stream_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KuppiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stream', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('scheduled_date', models.CharField(max_length=50)),
                ('scheduled_time', models.CharField(max_length=50)),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_live', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuppi_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
