# Generated by Django 6.0.2 on 2026-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kuppisession'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuppisession',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kuppisession',
            name='module_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kuppisession',
            name='session_type',
            field=models.CharField(default='Lecture', max_length=50),
        ),
        migrations.AlterField(
            model_name='kuppisession',
            name='academic_year',
            field=models.CharField(max_length=50),
        ),
    ]
