# Generated by Django 6.0.2 on 2026-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kuppisession_faculty_kuppisession_module_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuppisession',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kuppisession',
            name='faculty',
            field=models.CharField(default='Computing', max_length=100),
        ),
        migrations.AlterField(
            model_name='kuppisession',
            name='module_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kuppisession',
            name='session_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Notes Discussion', 'Notes Discussion'), ('Papers Discussion', 'Papers Discussion')], default='Lecture', max_length=50),
        ),
    ]
