# Generated by Django 6.0.2 on 2026-04-05 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resourcereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcereview',
            unique_together={('user', 'resource')},
        ),
    ]
