# Generated by Django 6.0.2 on 2026-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studyresource_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyresource',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
