# Generated by Django 6.0.3 on 2026-04-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studyresource_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyresource',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='is_smart_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='verification_status',
            field=models.CharField(choices=[('PROCESSING', 'AI Analyzing...'), ('PENDING', 'Pending Validation'), ('VERIFIED', 'Verified & Secure'), ('REJECTED', 'Validation Failed')], default='PROCESSING', max_length=20),
        ),
    ]
